//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.03 at 11:36:21 AM CST 
//


package com.ruoyi.yz.wuliu.ydkj.apply;

import com.ruoyi.yz.base.BaseCif;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}sender_name"/>
 *         &lt;element ref="{}sender_tel"/>
 *         &lt;element ref="{}sender_address"/>
 *         &lt;element ref="{}sender_eamil"/>
 *         &lt;element ref="{}sender_compay"/>
 *         &lt;element ref="{}sd_country_code"/>
 *         &lt;element ref="{}sd_city_code"/>
 *         &lt;element ref="{}sender_city"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderName",
    "senderTel",
    "senderAddress",
    "senderEamil",
    "senderCompay",
    "sdCountryCode",
    "sdCityCode",
    "senderCity"
})
@XmlRootElement(name = "sender")
public class YdApplySender extends BaseCif{

    @XmlElement(name = "sender_name", required = true)
    protected String senderName;
    @XmlElement(name = "sender_tel", required = true)
    protected String senderTel;
    @XmlElement(name = "sender_address", required = true)
    protected String senderAddress;
    @XmlElement(name = "sender_eamil", required = true)
    protected String senderEamil;
    @XmlElement(name = "sender_compay", required = true)
    protected String senderCompay;
    @XmlElement(name = "sd_country_code", required = true)
    protected String sdCountryCode;
    @XmlElement(name = "sd_city_code", required = true)
    protected String sdCityCode;
    @XmlElement(name = "sender_city", required = true)
    protected String senderCity;

    /**
     * Gets the value of the senderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * Sets the value of the senderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderName(String value) {
        this.senderName = value;
    }

    /**
     * Gets the value of the senderTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderTel() {
        return senderTel;
    }

    /**
     * Sets the value of the senderTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderTel(String value) {
        this.senderTel = value;
    }

    /**
     * Gets the value of the senderAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * Sets the value of the senderAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderAddress(String value) {
        this.senderAddress = value;
    }

    /**
     * Gets the value of the senderEamil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEamil() {
        return senderEamil;
    }

    /**
     * Sets the value of the senderEamil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEamil(String value) {
        this.senderEamil = value;
    }

    /**
     * Gets the value of the senderCompay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderCompay() {
        return senderCompay;
    }

    /**
     * Sets the value of the senderCompay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderCompay(String value) {
        this.senderCompay = value;
    }

    /**
     * Gets the value of the sdCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdCountryCode() {
        return sdCountryCode;
    }

    /**
     * Sets the value of the sdCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdCountryCode(String value) {
        this.sdCountryCode = value;
    }

    /**
     * Gets the value of the sdCityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdCityCode() {
        return sdCityCode;
    }

    /**
     * Sets the value of the sdCityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdCityCode(String value) {
        this.sdCityCode = value;
    }

    /**
     * Gets the value of the senderCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderCity() {
        return senderCity;
    }

    /**
     * Sets the value of the senderCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderCity(String value) {
        this.senderCity = value;
    }

}
