//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.03 at 11:36:21 AM CST 
//


package com.ruoyi.yz.wuliu.ydkj.apply;

import com.ruoyi.yz.base.BaseCif;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}receiver_name"/>
 *         &lt;element ref="{}receiver_tel"/>
 *         &lt;element ref="{}receiver_address"/>
 *         &lt;element ref="{}receiver_eamil"/>
 *         &lt;element ref="{}receiver_compay"/>
 *         &lt;element ref="{}re_card_type"/>
 *         &lt;element ref="{}re_card_no"/>
 *         &lt;element ref="{}re_country_code"/>
 *         &lt;element ref="{}re_city_code"/>
 *         &lt;element ref="{}receiver_province"/>
 *         &lt;element ref="{}receiver_city"/>
 *         &lt;element ref="{}receiver_area"/>
 *         &lt;element ref="{}receiver_street"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiverName",
    "receiverTel",
    "receiverAddress",
    "receiverEamil",
    "receiverCompay",
    "reCardType",
    "reCardNo",
    "reCountryCode",
    "reCityCode",
    "receiverProvince",
    "receiverCity",
    "receiverArea",
    "receiverStreet"
})
@XmlRootElement(name = "receiver")
public class YdApplyReceiver extends BaseCif{

    @XmlElement(name = "receiver_name", required = true)
    protected String receiverName;
    @XmlElement(name = "receiver_tel", required = true)
    protected String receiverTel;
    @XmlElement(name = "receiver_address", required = true)
    protected String receiverAddress;
    @XmlElement(name = "receiver_eamil", required = true)
    protected String receiverEamil;
    @XmlElement(name = "receiver_compay", required = true)
    protected String receiverCompay;
    @XmlElement(name = "re_card_type", required = true)
    protected String reCardType;
    @XmlElement(name = "re_card_no", required = true)
    protected String reCardNo;
    @XmlElement(name = "re_country_code", required = true)
    protected String reCountryCode;
    @XmlElement(name = "re_city_code", required = true)
    protected String reCityCode;
    @XmlElement(name = "receiver_province", required = true)
    protected String receiverProvince;
    @XmlElement(name = "receiver_city", required = true)
    protected String receiverCity;
    @XmlElement(name = "receiver_area", required = true)
    protected String receiverArea;
    @XmlElement(name = "receiver_street", required = true)
    protected String receiverStreet;

    /**
     * Gets the value of the receiverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * Sets the value of the receiverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverName(String value) {
        this.receiverName = value;
    }

    /**
     * Gets the value of the receiverTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * Sets the value of the receiverTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverTel(String value) {
        this.receiverTel = value;
    }

    /**
     * Gets the value of the receiverAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * Sets the value of the receiverAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverAddress(String value) {
        this.receiverAddress = value;
    }

    /**
     * Gets the value of the receiverEamil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverEamil() {
        return receiverEamil;
    }

    /**
     * Sets the value of the receiverEamil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverEamil(String value) {
        this.receiverEamil = value;
    }

    /**
     * Gets the value of the receiverCompay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverCompay() {
        return receiverCompay;
    }

    /**
     * Sets the value of the receiverCompay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverCompay(String value) {
        this.receiverCompay = value;
    }

    /**
     * Gets the value of the reCardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReCardType() {
        return reCardType;
    }

    /**
     * Sets the value of the reCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReCardType(String value) {
        this.reCardType = value;
    }

    /**
     * Gets the value of the reCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReCardNo() {
        return reCardNo;
    }

    /**
     * Sets the value of the reCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReCardNo(String value) {
        this.reCardNo = value;
    }

    /**
     * Gets the value of the reCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReCountryCode() {
        return reCountryCode;
    }

    /**
     * Sets the value of the reCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReCountryCode(String value) {
        this.reCountryCode = value;
    }

    /**
     * Gets the value of the reCityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReCityCode() {
        return reCityCode;
    }

    /**
     * Sets the value of the reCityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReCityCode(String value) {
        this.reCityCode = value;
    }

    /**
     * Gets the value of the receiverProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * Sets the value of the receiverProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverProvince(String value) {
        this.receiverProvince = value;
    }

    /**
     * Gets the value of the receiverCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * Sets the value of the receiverCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverCity(String value) {
        this.receiverCity = value;
    }

    /**
     * Gets the value of the receiverArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverArea() {
        return receiverArea;
    }

    /**
     * Sets the value of the receiverArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverArea(String value) {
        this.receiverArea = value;
    }

    /**
     * Gets the value of the receiverStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverStreet() {
        return receiverStreet;
    }

    /**
     * Sets the value of the receiverStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverStreet(String value) {
        this.receiverStreet = value;
    }

}
