//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:21:34 PM CST 
//


package com.ruoyi.yz.customs;

import com.ruoyi.yz.base.BaseCif;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}copCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}copName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}dxpMode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}dxpId"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}note"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "copCode",
    "copName",
    "dxpMode",
    "dxpId",
    "note"
})
@XmlRootElement(name = "BaseTransfer")
public class BaseTransfer  extends BaseCif{

    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String copCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String copName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String dxpMode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String dxpId;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String note;

    /**
     * Gets the value of the copCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopCode() {
        return copCode;
    }

    /**
     * Sets the value of the copCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopCode(String value) {
        this.copCode = value;
    }

    /**
     * Gets the value of the copName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopName() {
        return copName;
    }

    /**
     * Sets the value of the copName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopName(String value) {
        this.copName = value;
    }

    /**
     * Gets the value of the dxpMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDxpMode() {
        return dxpMode;
    }

    /**
     * Sets the value of the dxpMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDxpMode(String value) {
        this.dxpMode = value;
    }

    /**
     * Gets the value of the dxpId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDxpId() {
        return dxpId;
    }

    /**
     * Sets the value of the dxpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDxpId(String value) {
        this.dxpId = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

}
