//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.18 at 02:35:10 PM CST 
//


package com.ruoyi.yz.wuliu.ydkj.create;

import com.ruoyi.yz.base.BaseCif;
import com.ruoyi.yz.wuliu.ydkj.YdGoodsList;
import com.ruoyi.yz.wuliu.ydkj.YdReceiver;
import com.ruoyi.yz.wuliu.ydkj.YdSender;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}mail_no"/>
 *         &lt;element ref="{}hawbno"/>
 *         &lt;element ref="{}order_id"/>
 *         &lt;element ref="{}mawb"/>
 *         &lt;element ref="{}piece"/>
 *         &lt;element ref="{}weight"/>
 *         &lt;element ref="{}volumeWeight"/>
 *         &lt;element ref="{}freight"/>
 *         &lt;element ref="{}pre_express"/>
 *         &lt;element ref="{}next_express"/>
 *         &lt;element ref="{}fcountry"/>
 *         &lt;element ref="{}tcountry"/>
 *         &lt;element ref="{}infor_origin"/>
 *         &lt;element ref="{}receiver"/>
 *         &lt;element ref="{}sender"/>
 *         &lt;element ref="{}insurance_fee"/>
 *         &lt;element ref="{}goods_money"/>
 *         &lt;element ref="{}certificate_type"/>
 *         &lt;element ref="{}certificate_id"/>
 *         &lt;element ref="{}currency"/>
 *         &lt;element ref="{}request"/>
 *         &lt;element ref="{}remark"/>
 *         &lt;element ref="{}goods_list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mailNo",
    "hawbno",
    "orderId",
    "ptype",
    "mawb",
    "piece",
    "weight",
    "volumeWeight",
    "freight",
    "preExpress",
    "nextExpress",
    "fcountry",
    "tcountry",
    "inforOrigin",
    "receiver",
    "sender",
    "insuranceFee",
    "goodsMoney",
    "certificateType",
    "certificateId",
    "currency",
    "request",
    "remark",
    "goodsList"
})
@XmlRootElement(name = "hawb")
public class YdCreateHawb extends BaseCif{

    @XmlElement(name = "mail_no", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String mailNo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hawbno;
    @XmlElement(name = "order_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String orderId;
    @XmlElement(name = "ptype", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ptype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String mawb;
    @XmlElement(required = true)
    protected int piece;
    @XmlElement(required = true)
    protected BigDecimal weight;
    @XmlElement(required = true)
    protected BigDecimal volumeWeight;
    @XmlElement(required = true)
    protected BigDecimal freight;
    @XmlElement(name = "pre_express", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String preExpress;
    @XmlElement(name = "next_express", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nextExpress;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fcountry;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tcountry;
    @XmlElement(name = "infor_origin", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String inforOrigin;
    @XmlElement(required = true)
    protected YdReceiver receiver;
    @XmlElement(required = true)
    protected YdSender sender;
    @XmlElement(name = "insurance_fee", required = true)
    protected BigDecimal insuranceFee;
    @XmlElement(name = "goods_money", required = true)
    protected BigDecimal goodsMoney;
    @XmlElement(name = "certificate_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String certificateType;
    @XmlElement(name = "certificate_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String certificateId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currency;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String request;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String remark;
    @XmlElement(name = "goods_list", required = true)
    protected YdGoodsList goodsList;

    /**
     * Gets the value of the mailNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailNo() {
        return mailNo;
    }

    /**
     * Sets the value of the mailNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailNo(String value) {
        this.mailNo = value;
    }

    /**
     * Gets the value of the hawbno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHawbno() {
        return hawbno;
    }

    /**
     * Sets the value of the hawbno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHawbno(String value) {
        this.hawbno = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the mawb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMawb() {
        return mawb;
    }

    /**
     * Sets the value of the mawb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMawb(String value) {
        this.mawb = value;
    }

    /**
     * Gets the value of the piece property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getPiece() {
        return piece;
    }

    /**
     * Sets the value of the piece property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiece(int value) {
        this.piece = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the volumeWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getVolumeWeight() {
        return volumeWeight;
    }

    /**
     * Sets the value of the volumeWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeWeight(BigDecimal value) {
        this.volumeWeight = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreight(BigDecimal value) {
        this.freight = value;
    }

    /**
     * Gets the value of the preExpress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreExpress() {
        return preExpress;
    }

    /**
     * Sets the value of the preExpress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreExpress(String value) {
        this.preExpress = value;
    }

    /**
     * Gets the value of the nextExpress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextExpress() {
        return nextExpress;
    }

    /**
     * Sets the value of the nextExpress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextExpress(String value) {
        this.nextExpress = value;
    }

    /**
     * Gets the value of the fcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFcountry() {
        return fcountry;
    }

    /**
     * Sets the value of the fcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFcountry(String value) {
        this.fcountry = value;
    }

    /**
     * Gets the value of the tcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcountry() {
        return tcountry;
    }

    /**
     * Sets the value of the tcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcountry(String value) {
        this.tcountry = value;
    }

    /**
     * Gets the value of the inforOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInforOrigin() {
        return inforOrigin;
    }

    /**
     * Sets the value of the inforOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInforOrigin(String value) {
        this.inforOrigin = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link Receiver }
     *     
     */
    public YdReceiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receiver }
     *     
     */
    public void setReceiver(YdReceiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link Sender }
     *     
     */
    public YdSender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sender }
     *     
     */
    public void setSender(YdSender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the insuranceFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getInsuranceFee() {
        return insuranceFee;
    }

    /**
     * Sets the value of the insuranceFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuranceFee(BigDecimal value) {
        this.insuranceFee = value;
    }

    /**
     * Gets the value of the goodsMoney property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getGoodsMoney() {
        return goodsMoney;
    }

    /**
     * Sets the value of the goodsMoney property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsMoney(BigDecimal value) {
        this.goodsMoney = value;
    }

    /**
     * Gets the value of the certificateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * Sets the value of the certificateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateType(String value) {
        this.certificateType = value;
    }

    /**
     * Gets the value of the certificateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateId() {
        return certificateId;
    }

    /**
     * Sets the value of the certificateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateId(String value) {
        this.certificateId = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequest(String value) {
        this.request = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the goodsList property.
     * 
     * @return
     *     possible object is
     *     {@link YdGoodsList }
     *     
     */
    public YdGoodsList getGoodsList() {
        return goodsList;
    }

    /**
     * Sets the value of the goodsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link YdGoodsList }
     *     
     */
    public void setGoodsList(YdGoodsList value) {
        this.goodsList = value;
    }

    /**
     * @return the ptype
     */
    public String getPtype() {
        return ptype;
    }

    /**
     * @param ptype the ptype to set
     */
    public void setPtype(String ptype) {
        this.ptype = ptype;
    }

}
