//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:22:51 PM CST 
//
package com.ruoyi.yz.customs.details;

import com.ruoyi.yz.base.BaseCif;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import static org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation.EMPTY_NODE;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gnum"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemRecordNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gcode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gname"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gmodel"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}barCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}country"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}currency"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}qty"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}unit"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}qty1"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}unit1"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.chinaport.gov.cn/ceb}qty2"/>
 *           &lt;element ref="{http://www.chinaport.gov.cn/ceb}unit2"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}price"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}totalPrice"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}note"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gnum",
    "itemRecordNo",
    "itemNo",
    "itemName",
    "gcode",
    "gname",
    "gmodel",
    "barCode",
    "country",
    "currency",
    "qty",
    "unit",
    "qty1",
    "unit1",
    "qty2",
    "unit2",
    "price",
    "totalPrice",
    "note"
})
@XmlRootElement(name = "InventoryList", namespace = "http://www.chinaport.gov.cn/ceb")
public class InventoryList extends BaseCif {
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected BigInteger gnum;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String itemRecordNo;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String itemNo;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String itemName;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String gcode;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String gname;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String gmodel;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String barCode;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String country;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String currency;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected BigDecimal qty;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String unit;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected BigDecimal qty1;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String unit1;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected BigDecimal qty2;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String unit2;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected BigDecimal price;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected BigDecimal totalPrice;
    @XmlElement(required = true, namespace = "http://www.chinaport.gov.cn/ceb")
    protected String note;

    /**
     * Gets the value of the gnum property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getGnum() {
        return gnum;
    }

    /**
     * Sets the value of the gnum property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setGnum(BigInteger value) {
        this.gnum = value;
    }

    /**
     * Gets the value of the itemRecordNo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getItemRecordNo() {
        return itemRecordNo;
    }

    /**
     * Sets the value of the itemRecordNo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setItemRecordNo(String value) {
        this.itemRecordNo = value;
    }

    /**
     * Gets the value of the itemNo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setItemNo(String value) {
        this.itemNo = value;
    }

    /**
     * Gets the value of the itemName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the gcode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGcode() {
        return gcode;
    }

    /**
     * Sets the value of the gcode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGcode(String value) {
        this.gcode = value;
    }

    /**
     * Gets the value of the gname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGname() {
        return gname;
    }

    /**
     * Sets the value of the gname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGname(String value) {
        this.gname = value;
    }

    /**
     * Gets the value of the gmodel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGmodel() {
        return gmodel;
    }

    /**
     * Sets the value of the gmodel property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGmodel(String value) {
        this.gmodel = value;
    }

    /**
     * Gets the value of the barCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBarCode(String value) {
        this.barCode = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the qty property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setQty(BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the unit property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the qty1 property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getQty1() {
        return qty1;
    }

    /**
     * Sets the value of the qty1 property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setQty1(BigDecimal value) {
        this.qty1 = value;
    }

    /**
     * Gets the value of the unit1 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnit1() {
        return unit1;
    }

    /**
     * Sets the value of the unit1 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnit1(String value) {
        this.unit1 = value;
    }

    /**
     * Gets the value of the qty2 property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getQty2() {
        return qty2;
    }

    /**
     * Sets the value of the qty2 property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setQty2(BigDecimal value) {
        this.qty2 = value;
    }

    /**
     * Gets the value of the unit2 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUnit2() {
        return unit2;
    }

    /**
     * Sets the value of the unit2 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUnit2(String value) {
        this.unit2 = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the totalPrice property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTotalPrice(BigDecimal value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the note property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNote(String value) {
        this.note = value;
    }

}
