//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:22:51 PM CST 
//


package com.ruoyi.yz.customs.details;

import com.ruoyi.yz.base.BaseCif;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import static org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation.EMPTY_NODE;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}guid"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appTime"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appStatus"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}orderNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebpCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebpName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebcCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebcName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}logisticsNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}logisticsCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}logisticsName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}copNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}assureCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ieFlag"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}declTime"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}customsCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}portCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ieDate"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerIdType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerIdNumber"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerTelephone"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}consigneeAddress"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}agentCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}agentName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}areaCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}areaName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}tradeMode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}trafMode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}trafNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}voyageNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}billNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}loctNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}licenseNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}country"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}freight"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}insuredFee"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}currency"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}wrapType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}packNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}grossWeight"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}netWeight"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}note"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "appType",
    "appTime",
    "appStatus",
    "orderNo",
    "ebpCode",
    "ebpName",
    "ebcCode",
    "ebcName",
    "logisticsNo",
    "logisticsCode",
    "logisticsName",
    "copNo",
    "preNo",
    "assureCode",
    "emsNo",
    "invtNo",
    "ieFlag",
    "declTime",
    "customsCode",
    "portCode",
    "ieDate",
    "buyerIdType",
    "buyerIdNumber",
    "buyerName",
    "buyerTelephone",
    "consigneeAddress",
    "agentCode",
    "agentName",
    "areaCode",
    "areaName",
    "tradeMode",
    "trafMode",
    "trafNo",
    "voyageNo",
    "billNo",
    "loctNo",
    "licenseNo",
    "country",
    "freight",
    "insuredFee",
    "currency",
    "wrapType",
    "packNo",
    "grossWeight",
    "netWeight",
    "note"
})
@XmlRootElement(name = "InventoryHead", namespace="http://www.chinaport.gov.cn/ceb")
public class InventoryHead  extends BaseCif{

    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String guid;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String appType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String appTime;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String appStatus;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String orderNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String ebpCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String ebpName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String ebcCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String ebcName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String logisticsNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String logisticsCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String logisticsName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String copNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String assureCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String ieFlag;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String declTime;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String customsCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String portCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String ieDate;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String buyerIdType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String buyerIdNumber;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String buyerName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String buyerTelephone;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String consigneeAddress;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String agentCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String agentName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String areaCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String areaName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String tradeMode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String trafMode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    private String preNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    private String invtNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String trafNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String voyageNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String billNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String loctNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String licenseNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String country;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected BigDecimal freight;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected BigDecimal insuredFee;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected String currency;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String wrapType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected BigInteger packNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected BigDecimal grossWeight;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected BigDecimal netWeight;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    protected String note;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlNullPolicy(emptyNodeRepresentsNull = true, nullRepresentationForXml = EMPTY_NODE)
    private String emsNo;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the appType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppType() {
        return appType;
    }

    /**
     * Sets the value of the appType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppType(String value) {
        this.appType = value;
    }

    /**
     * Gets the value of the appTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppTime() {
        return appTime;
    }

    /**
     * Sets the value of the appTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppTime(String value) {
        this.appTime = value;
    }

    /**
     * Gets the value of the appStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * Sets the value of the appStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppStatus(String value) {
        this.appStatus = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the ebpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbpCode() {
        return ebpCode;
    }

    /**
     * Sets the value of the ebpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbpCode(String value) {
        this.ebpCode = value;
    }

    /**
     * Gets the value of the ebpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbpName() {
        return ebpName;
    }

    /**
     * Sets the value of the ebpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbpName(String value) {
        this.ebpName = value;
    }

    /**
     * Gets the value of the ebcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbcCode() {
        return ebcCode;
    }

    /**
     * Sets the value of the ebcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbcCode(String value) {
        this.ebcCode = value;
    }

    /**
     * Gets the value of the ebcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbcName() {
        return ebcName;
    }

    /**
     * Sets the value of the ebcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbcName(String value) {
        this.ebcName = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticsNo(String value) {
        this.logisticsNo = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticsCode(String value) {
        this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticsName(String value) {
        this.logisticsName = value;
    }

    /**
     * Gets the value of the copNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopNo() {
        return copNo;
    }

    /**
     * Sets the value of the copNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopNo(String value) {
        this.copNo = value;
    }

    /**
     * Gets the value of the assureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssureCode() {
        return assureCode;
    }

    /**
     * Sets the value of the assureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssureCode(String value) {
        this.assureCode = value;
    }

    /**
     * Gets the value of the ieFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIeFlag() {
        return ieFlag;
    }

    /**
     * Sets the value of the ieFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIeFlag(String value) {
        this.ieFlag = value;
    }

    /**
     * Gets the value of the declTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclTime() {
        return declTime;
    }

    /**
     * Sets the value of the declTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclTime(String value) {
        this.declTime = value;
    }

    /**
     * Gets the value of the customsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomsCode() {
        return customsCode;
    }

    /**
     * Sets the value of the customsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomsCode(String value) {
        this.customsCode = value;
    }

    /**
     * Gets the value of the portCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortCode() {
        return portCode;
    }

    /**
     * Sets the value of the portCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortCode(String value) {
        this.portCode = value;
    }

    /**
     * Gets the value of the ieDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIeDate() {
        return ieDate;
    }

    /**
     * Sets the value of the ieDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIeDate(String value) {
        this.ieDate = value;
    }

    /**
     * Gets the value of the buyerIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerIdType() {
        return buyerIdType;
    }

    /**
     * Sets the value of the buyerIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerIdType(String value) {
        this.buyerIdType = value;
    }

    /**
     * Gets the value of the buyerIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerIdNumber() {
        return buyerIdNumber;
    }

    /**
     * Sets the value of the buyerIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerIdNumber(String value) {
        this.buyerIdNumber = value;
    }

    /**
     * Gets the value of the buyerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * Sets the value of the buyerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerName(String value) {
        this.buyerName = value;
    }

    /**
     * Gets the value of the buyerTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerTelephone() {
        return buyerTelephone;
    }

    /**
     * Sets the value of the buyerTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerTelephone(String value) {
        this.buyerTelephone = value;
    }

    /**
     * Gets the value of the consigneeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * Sets the value of the consigneeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeAddress(String value) {
        this.consigneeAddress = value;
    }

    /**
     * Gets the value of the agentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * Sets the value of the agentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentCode(String value) {
        this.agentCode = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentName(String value) {
        this.agentName = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the areaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * Sets the value of the areaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaName(String value) {
        this.areaName = value;
    }

    /**
     * Gets the value of the tradeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMode() {
        return tradeMode;
    }

    /**
     * Sets the value of the tradeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMode(String value) {
        this.tradeMode = value;
    }

    /**
     * Gets the value of the trafMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafMode() {
        return trafMode;
    }

    /**
     * Sets the value of the trafMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafMode(String value) {
        this.trafMode = value;
    }

    /**
     * Gets the value of the trafNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafNo() {
        return trafNo;
    }

    /**
     * Sets the value of the trafNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafNo(String value) {
        this.trafNo = value;
    }

    /**
     * Gets the value of the voyageNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyageNo() {
        return voyageNo;
    }

    /**
     * Sets the value of the voyageNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyageNo(String value) {
        this.voyageNo = value;
    }

    /**
     * Gets the value of the billNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * Sets the value of the billNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNo(String value) {
        this.billNo = value;
    }

    /**
     * Gets the value of the loctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoctNo() {
        return loctNo;
    }

    /**
     * Sets the value of the loctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoctNo(String value) {
        this.loctNo = value;
    }

    /**
     * Gets the value of the licenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * Sets the value of the licenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNo(String value) {
        this.licenseNo = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreight(BigDecimal value) {
        this.freight = value;
    }

    /**
     * Gets the value of the insuredFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuredFee() {
        return insuredFee;
    }

    /**
     * Sets the value of the insuredFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuredFee(BigDecimal value) {
        this.insuredFee = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the wrapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrapType() {
        return wrapType;
    }

    /**
     * Sets the value of the wrapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrapType(String value) {
        this.wrapType = value;
    }

    /**
     * Gets the value of the packNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPackNo() {
        return packNo;
    }

    /**
     * Sets the value of the packNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPackNo(BigInteger value) {
        this.packNo = value;
    }

    /**
     * Gets the value of the grossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossWeight(BigDecimal value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetWeight(BigDecimal value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * @return the emsNo
     */
    public String getEmsNo() {
        return emsNo;
    }

    /**
     * @param emsNo the emsNo to set
     */
    public void setEmsNo(String emsNo) {
        this.emsNo = emsNo;
    }

    /**
     * @return the preNo
     */
    public String getPreNo() {
        return preNo;
    }

    /**
     * @param preNo the preNo to set
     */
    public void setPreNo(String preNo) {
        this.preNo = preNo;
    }

    /**
     * @return the invtNo
     */
    public String getInvtNo() {
        return invtNo;
    }

    /**
     * @param invtNo the invtNo to set
     */
    public void setInvtNo(String invtNo) {
        this.invtNo = invtNo;
    }

}
