//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:22:51 PM CST 
//


package com.ruoyi.yz.customs.details;

import com.ruoyi.yz.base.BaseCif;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}InventoryHead"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}InventoryList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inventoryHead",
    "inventoryList"
})
@XmlRootElement(name = "Inventory", namespace="http://www.chinaport.gov.cn/ceb")
public class Inventory  extends BaseCif{

    @XmlElement(name = "InventoryHead", required = true, namespace="http://www.chinaport.gov.cn/ceb")
    protected InventoryHead inventoryHead;
    @XmlElement(name = "InventoryList", required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private List<InventoryList> inventoryList;

    /**
     * Gets the value of the inventoryHead property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryHead }
     *     
     */
    public InventoryHead getInventoryHead() {
        return inventoryHead;
    }

    /**
     * Sets the value of the inventoryHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryHead }
     *     
     */
    public void setInventoryHead(InventoryHead value) {
        this.inventoryHead = value;
    }

    /**
     * Gets the value of the inventoryList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inventoryList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInventoryList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InventoryList }
     * 
     * 
     * @return 
     */
    public List<InventoryList> getInventoryList() {
        if (inventoryList == null) {
            inventoryList = new ArrayList<>();
        }
        return this.inventoryList;
    }

    /**
     * @param inventoryList the inventoryList to set
     */
    public void setInventoryList(List<InventoryList> inventoryList) {
        this.inventoryList = inventoryList;
    }

}
