//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.18 at 02:35:41 PM CST 
//


package com.ruoyi.yz.wuliu.ydkj.update;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}code"/>
 *         &lt;element ref="{}hawbno"/>
 *         &lt;element ref="{}mail_no"/>
 *         &lt;element ref="{}msg"/>
 *         &lt;element ref="{}pdf_info"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hawbno",
    "mailNo",
    "code",
    "msg",
    "pdfInfo"
})
@XmlRootElement(name = "response")
public class YdUpdateResponse {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private String hawbno;
    @XmlElement(name = "mail_no", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private String mailNo;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private String code;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private String msg;
    @XmlElement(name = "pdf_info", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private String pdfInfo;

    /**
     * @return the hawbno
     */
    public String getHawbno() {
        return hawbno;
    }

    /**
     * @param hawbno the hawbno to set
     */
    public void setHawbno(String hawbno) {
        this.hawbno = hawbno;
    }

    /**
     * @return the mailNo
     */
    public String getMailNo() {
        return mailNo;
    }

    /**
     * @param mailNo the mailNo to set
     */
    public void setMailNo(String mailNo) {
        this.mailNo = mailNo;
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the code to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the msg
     */
    public String getMsg() {
        return msg;
    }

    /**
     * @param msg the msg to set
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * @return the pdfInfo
     */
    public String getPdfInfo() {
        return pdfInfo;
    }

    /**
     * @param pdfInfo the pdfInfo to set
     */
    public void setPdfInfo(String pdfInfo) {
        this.pdfInfo = pdfInfo;
    }

}
