//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:21:58 PM CST 
//


package com.ruoyi.yz.customs.wuliu;

import com.ruoyi.yz.base.BaseCif;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}LogisticsHead"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logisticsHead"
})
@XmlRootElement(name = "Logistics")
public class Logistics  extends BaseCif{

    @XmlElement(name = "LogisticsHead", required = true)
    protected LogisticsHead logisticsHead;

    /**
     * Gets the value of the logisticsHead property.
     * 
     * @return
     *     possible object is
     *     {@link LogisticsHead }
     *     
     */
    public LogisticsHead getLogisticsHead() {
        return logisticsHead;
    }

    /**
     * Sets the value of the logisticsHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogisticsHead }
     *     
     */
    public void setLogisticsHead(LogisticsHead value) {
        this.logisticsHead = value;
    }

}
