//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:20:43 PM CST 
//


package com.ruoyi.yz.customs.order;

import com.ruoyi.common.adapter.CDataAdapter;
import com.ruoyi.yz.base.BaseCif;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gnum"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}itemDescribe"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}barCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}unit"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}gmodel"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}qty"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}price"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}totalPrice"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}currency"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}country"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}note"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gnum",
    "itemNo",
    "itemName",
    "itemDescribe",
    "barCode",
    "unit",
    "gmodel",
    "qty",
    "price",
    "totalPrice",
    "currency",
    "country",
    "note"
})
@XmlRootElement(name = "OrderList", namespace="http://www.chinaport.gov.cn/ceb")
public class OrderList  extends BaseCif{

    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigInteger gnum;
    @XmlTransient
    private String itemRecordNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String itemNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlJavaTypeAdapter(CDataAdapter.class)
    private String itemName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String itemDescribe;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String barCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String unit;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlJavaTypeAdapter(CDataAdapter.class)
    private String gmodel;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal qty;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal price;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal totalPrice;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String currency;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String country;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    @XmlJavaTypeAdapter(CDataAdapter.class)
    private String note;
    @XmlTransient
    private String customsBianMa;
    @XmlTransient
    private BigDecimal qty1;
    @XmlTransient
    private String unit1;
    @XmlTransient
    private BigDecimal qty2;
    @XmlTransient
    private String unit2;

    /**
     * Gets the value of the gnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGnum() {
        return gnum;
    }

    /**
     * Sets the value of the gnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGnum(BigInteger value) {
        this.gnum = value;
    }

    /**
     * Gets the value of the itemNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemNo(String value) {
        this.itemNo = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the itemDescribe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDescribe() {
        return itemDescribe;
    }

    /**
     * Sets the value of the itemDescribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDescribe(String value) {
        this.itemDescribe = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarCode(String value) {
        this.barCode = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the gmodel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmodel() {
        return gmodel;
    }

    /**
     * Sets the value of the gmodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmodel(String value) {
        this.gmodel = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQty(BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPrice(BigDecimal value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * @return the itemRecordNo
     */
    public String getItemRecordNo() {
        return itemRecordNo;
    }

    /**
     * @param itemRecordNo the itemRecordNo to set
     */
    public void setItemRecordNo(String itemRecordNo) {
        this.itemRecordNo = itemRecordNo;
    }

    /**
     * @return the customsBianMa
     */
    public String getCustomsBianMa() {
        return customsBianMa;
    }

    /**
     * @param customsBianMa the customsBianMa to set
     */
    public void setCustomsBianMa(String customsBianMa) {
        this.customsBianMa = customsBianMa;
    }

    /**
     * @return the qty1
     */
    public BigDecimal getQty1() {
        return qty1;
    }

    /**
     * @param qty1 the qty1 to set
     */
    public void setQty1(BigDecimal qty1) {
        this.qty1 = qty1;
    }

    /**
     * @return the unit1
     */
    public String getUnit1() {
        return unit1;
    }

    /**
     * @param unit1 the unit1 to set
     */
    public void setUnit1(String unit1) {
        this.unit1 = unit1;
    }

    /**
     * @return the qty2
     */
    public BigDecimal getQty2() {
        return qty2;
    }

    /**
     * @param qty2 the qty2 to set
     */
    public void setQty2(BigDecimal qty2) {
        this.qty2 = qty2;
    }

    /**
     * @return the unit2
     */
    public String getUnit2() {
        return unit2;
    }

    /**
     * @param unit2 the unit2 to set
     */
    public void setUnit2(String unit2) {
        this.unit2 = unit2;
    }

}
