//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:20:43 PM CST 
//
package com.ruoyi.yz.customs.order;

import com.ruoyi.yz.base.BaseCif;
import com.ruoyi.yz.wuliu.Receiver;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}guid"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appTime"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}appStatus"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}orderType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}orderNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebpCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebpName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebcCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}ebcName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}goodsValue"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}freight"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}discount"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}taxTotal"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}acturalPaid"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}currency"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerRegNo"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerIdType"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerIdNumber"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}payCode"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}payName"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}payTransactionId"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}batchNumbers"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}consignee"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}consigneeTelephone"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}consigneeAddress"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}buyerTelephone"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}note"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "appType",
    "appTime",
    "appStatus",
    "orderType",
    "orderNo",
    "ebpCode",
    "ebpName",
    "ebcCode",
    "ebcName",
    "goodsValue",
    "freight",
    "discount",
    "taxTotal",
    "acturalPaid",
    "currency",
    "buyerRegNo",
    "buyerName",
    "buyerIdType",
    "buyerIdNumber",
    "payCode",
    "payName",
    "payTransactionId",
    "batchNumbers",
    "consignee",
    "consigneeTelephone",
    "consigneeAddress",
    "buyerTelephone",
    "note"
})
@XmlRootElement(name = "OrderHead", namespace="http://www.chinaport.gov.cn/ceb")
public class OrderHead extends BaseCif {
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String guid;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String appType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb") 
    private String appTime;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String appStatus;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String orderType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String orderNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String ebpCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String ebpName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String ebcCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String ebcName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal goodsValue;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal freight;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal discount;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal taxTotal;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private BigDecimal acturalPaid;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String currency;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String buyerRegNo;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String buyerName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String buyerIdType;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String buyerIdNumber;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String payCode;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String payName;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String payTransactionId;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String batchNumbers;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String consignee;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String consigneeTelephone;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String consigneeAddress;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String buyerTelephone;
    @XmlElement(required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private String note;
    @XmlTransient
    private Receiver receiver;
    @XmlTransient
    private String tid;
    @XmlTransient
    private String copNo;
    @XmlTransient
    private Date orderTime;
    @XmlTransient
    private BigDecimal qty;
    @XmlTransient
    private String emsNo;
    @XmlTransient
    private BigDecimal weight;

    /**
     * Gets the value of the guid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the appType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAppType() {
        return appType;
    }

    /**
     * Sets the value of the appType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAppType(String value) {
        this.appType = value;
    }

    /**
     * Gets the value of the appTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAppTime() {
        return appTime;
    }

    /**
     * Sets the value of the appTime property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAppTime(String value) {
        this.appTime = value;
    }

    /**
     * Gets the value of the appStatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * Sets the value of the appStatus property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAppStatus(String value) {
        this.appStatus = value;
    }

    /**
     * Gets the value of the orderType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the orderNo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the ebpCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEbpCode() {
        return ebpCode;
    }

    /**
     * Sets the value of the ebpCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEbpCode(String value) {
        this.ebpCode = value;
    }

    /**
     * Gets the value of the ebpName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEbpName() {
        return ebpName;
    }

    /**
     * Sets the value of the ebpName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEbpName(String value) {
        this.ebpName = value;
    }

    /**
     * Gets the value of the ebcCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEbcCode() {
        return ebcCode;
    }

    /**
     * Sets the value of the ebcCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEbcCode(String value) {
        this.ebcCode = value;
    }

    /**
     * Gets the value of the ebcName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEbcName() {
        return ebcName;
    }

    /**
     * Sets the value of the ebcName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEbcName(String value) {
        this.ebcName = value;
    }

    /**
     * Gets the value of the goodsValue property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getGoodsValue() {
        return goodsValue;
    }

    /**
     * Sets the value of the goodsValue property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setGoodsValue(BigDecimal value) {
        this.goodsValue = value;
    }

    /**
     * Gets the value of the freight property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setFreight(BigDecimal value) {
        this.freight = value;
    }

    /**
     * Gets the value of the discount property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setDiscount(BigDecimal value) {
        this.discount = value;
    }

    /**
     * Gets the value of the taxTotal property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTaxTotal() {
        return taxTotal;
    }

    /**
     * Sets the value of the taxTotal property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTaxTotal(BigDecimal value) {
        this.taxTotal = value;
    }

    /**
     * Gets the value of the acturalPaid property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getActuralPaid() {
        return acturalPaid;
    }

    /**
     * Sets the value of the acturalPaid property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setActuralPaid(BigDecimal value) {
        this.acturalPaid = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the buyerRegNo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBuyerRegNo() {
        return buyerRegNo;
    }

    /**
     * Sets the value of the buyerRegNo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBuyerRegNo(String value) {
        this.buyerRegNo = value;
    }

    /**
     * Gets the value of the buyerName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * Sets the value of the buyerName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBuyerName(String value) {
        this.buyerName = value;
    }

    /**
     * Gets the value of the buyerIdType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBuyerIdType() {
        return buyerIdType;
    }

    /**
     * Sets the value of the buyerIdType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBuyerIdType(String value) {
        this.buyerIdType = value;
    }

    /**
     * Gets the value of the buyerIdNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBuyerIdNumber() {
        return buyerIdNumber;
    }

    /**
     * Sets the value of the buyerIdNumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBuyerIdNumber(String value) {
        this.buyerIdNumber = value;
    }

    /**
     * Gets the value of the payCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * Sets the value of the payCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPayCode(String value) {
        this.payCode = value;
    }

    /**
     * Gets the value of the payName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPayName() {
        return payName;
    }

    /**
     * Sets the value of the payName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPayName(String value) {
        this.payName = value;
    }

    /**
     * Gets the value of the payTransactionId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPayTransactionId() {
        return payTransactionId;
    }

    /**
     * Sets the value of the payTransactionId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPayTransactionId(String value) {
        this.payTransactionId = value;
    }

    /**
     * Gets the value of the batchNumbers property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBatchNumbers() {
        return batchNumbers;
    }

    /**
     * Sets the value of the batchNumbers property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBatchNumbers(String value) {
        this.batchNumbers = value;
    }

    /**
     * Gets the value of the consignee property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setConsignee(String value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the consigneeTelephone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getConsigneeTelephone() {
        return consigneeTelephone;
    }

    /**
     * Sets the value of the consigneeTelephone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setConsigneeTelephone(String value) {
        this.consigneeTelephone = value;
    }

    /**
     * Gets the value of the consigneeAddress property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * Sets the value of the consigneeAddress property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setConsigneeAddress(String value) {
        this.consigneeAddress = value;
    }

    /**
     * Gets the value of the buyerTelephone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBuyerTelephone() {
        return buyerTelephone;
    }

    /**
     * Sets the value of the buyerTelephone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBuyerTelephone(String value) {
        this.buyerTelephone = value;
    }

    /**
     * Gets the value of the note property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * @return the receiver
     */
    public Receiver getReceiver() {
        return receiver;
    }

    /**
     * @param receiver the receiver to set
     */
    public void setReceiver(Receiver receiver) {
        this.receiver = receiver;
    }

    /**
     * @return the tid
     */
    public String getTid() {
        return tid;
    }

    /**
     * @param tid the tid to set
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * @return the orderTime
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * @param orderTime the orderTime to set
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * @return the qty
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * @param qty the qty to set
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * @return the emsNo
     */
    public String getEmsNo() {
        return emsNo;
    }

    /**
     * @param emsNo the emsNo to set
     */
    public void setEmsNo(String emsNo) {
        this.emsNo = emsNo;
    }

    /**
     * @return the copNo
     */
    public String getCopNo() {
        return copNo;
    }

    /**
     * @param copNo the copNo to set
     */
    public void setCopNo(String copNo) {
        this.copNo = copNo;
    }

    /**
     * @return the weight
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * @param weight the weight to set
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

}
