//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.28 at 10:20:43 PM CST 
//


package com.ruoyi.yz.customs.order;

import com.ruoyi.yz.base.BaseCif;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}OrderHead"/>
 *         &lt;element ref="{http://www.chinaport.gov.cn/ceb}OrderList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderHead",
    "orderList"
})
@XmlRootElement(name = "Order", namespace="http://www.chinaport.gov.cn/ceb")
public class Order  extends BaseCif{

    @XmlElement(name = "OrderHead", required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private OrderHead orderHead;
    @XmlElement(name = "OrderList", required = true, namespace="http://www.chinaport.gov.cn/ceb")
    private List<OrderList> orderList;

    /**
     * Gets the value of the orderHead property.
     * 
     * @return
     *     possible object is
     *     {@link OrderHead }
     *     
     */
    public OrderHead getOrderHead() {
        return orderHead;
    }

    /**
     * Sets the value of the orderHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderHead }
     *     
     */
    public void setOrderHead(OrderHead value) {
        this.orderHead = value;
    }

    /**
     * Gets the value of the orderList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderList }
     * 
     * 
     * @return 
     */
    public List<OrderList> getOrderList() {
        return this.orderList;
    }

    public void setOrderList(List<OrderList> orderList){
        this.orderList = orderList;
    }
}
